name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [7.3, 7.4, 8.0]
        dependency-version: [prefer-lowest, prefer-stable]

    name: Tests P${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, hash, openssl
          tools: composer:v2
          coverage: pcov

      - name: Install PHP 7 dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
        if: "matrix.php < 8"

      - name: Install PHP 8 dependencies
        run: composer update --${{ matrix.dependency-version }} --ignore-platform-req=php --no-interaction --no-progress
        if: "matrix.php >= 8"

      - name: Pest Unit Tests
        run: vendor/bin/pest --colors=always

      - name: PHPStan Type Checks
        run: vendor/bin/phpstan analyse --ansi

      - name: Psalm Type Tests
        run: vendor/bin/psalm --shepherd -c psalm.xml
